version: '2'
services:
  bid-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.service
    ports:
      - "8081:8081"
    links:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    command: redis-server --appendonly yes
    restart: always